### PR TITLE
Add "version" to datacite record and bundle datacite json serializations

### PR DESCRIPTION
**Pull request by yarikoptic**
folded in a typo fix

partially addresses

- #259 

This PR also bundles (**all** known versions) datacite json schemas.

### CODE REVIEW

**Comment by yarikoptic** [comment]
all tests are failing with similar

```
E   requests.exceptions.ProxyError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /datacite/schema/732cc7ef29f4cad4d6adfac83544133cd57a2e5e/source/json/kernel-4.3/datacite_4.3_schema.json (Caused by ProxyError('Unable to connect to proxy', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f87bab74170>: Failed to establish a new connection: [Errno 111] Connection refused')))
```

I think it might be worth just shipping copies of desired verion(s) of datacite serializations right in here, in particular since we are referencing a specific to commit version.

**Comment by yarikoptic** [comment]
dandi-cli versions failing to install with

> ERROR: Package 'dandi' requires a different Python: 3.8.18 not in '>=3.9'

since here we have not yet dropped 3.8 and in dandi-cli already did...

**Comment by djarecka** [comment]
i'm wondering if we really want to keep all the version from these repositories, or decide on one that we want to match. Or perhaps we want to create our own?

**Comment by yarikoptic** [comment]
we had to do `diff` archaeological expedition so I thought to accumulate them all in one common space.  They are relatively lightweight so I saw no reservation from keeping them all. 
```
❯ du -sck dandischema/datacite/schema/*
16	dandischema/datacite/schema/datacite-4.3-17-gaa5db56.json
20	dandischema/datacite/schema/datacite-4.3-72-g732cc7e.json
20	dandischema/datacite/schema/inveniosoftware-4.3-66-g24fc2ba.json
24	dandischema/datacite/schema/inveniosoftware-4.5-81-g160250d.json
4	dandischema/datacite/schema/README.md
84	total
```
Moreover, with exposing version in the code we could try one or another easily and consistently across versions.

**Pull request merged**
