### PR TITLE
added funderidtype and support for funder and sponsor roles to datacite metadata

### LINKED ISSUE #168: datacite: shouldn't we use Funders not Sponsors?
While digging around #166 I saw that we do "treat" `Sponsor` as information about funding, and actually entirely omit `Funder`s  https://github.com/dandi/dandi-schema/blob/master/dandischema/datacite.py#L113 although we have more of those

```
drogon:/mnt/backup/dandi/dandisets
*$> grep dcite:Funder */dandiset.yaml | nl | tail
    95  000409/dandiset.yaml:  - dcite:Funder
    96  000409/dandiset.yaml:  - dcite:Funder
    97  000409/dandiset.yaml:  - dcite:Funder
    98  000444/dandiset.yaml:  - dcite:Funder
    99  000447/dandiset.yaml:  - dcite:Funder
   100  000448/dandiset.yaml:  - dcite:Funder
   101  000454/dandiset.yaml:  - dcite:Funder
   102  000454/dandiset.yaml:  - dcite:Funder
   103  000454/dandiset.yaml:  - dcite:Funder
   104  000458/dandiset.yaml:  - dcite:Funder

*$> grep dcite:Sponsor */dandiset.yaml | nl | tail
     4  000004/dandiset.yaml:  - dcite:Sponsor
     5  000004/dandiset.yaml:  - dcite:Sponsor
     6  000004/dandiset.yaml:  - dcite:Sponsor
     7  000004/dandiset.yaml:  - dcite:Sponsor
     8  000018/dandiset.yaml:  - dcite:Sponsor
     9  000026/dandiset.yaml:  - dcite:Sponsor
    10  000029/dandiset.yaml:  - dcite:Sponsor
    11  000070/dandiset.yaml:  - dcite:Sponsor
    12  000121/dandiset.yaml:  - dcite:Sponsor
    13  000458/dandiset.yaml:  - dcite:Sponsor
```

and which might explain (partially) why we have not encountered #166 before.

@satra @djarecka ideas?

### PR DESCRIPTION
**Pull request by satra**
closes #168 

- added funderidtype
- added support for funders and sponsors

according to @djarecka's test the current release mints a doi for the failing metadata schema on dandiarchive, so unsure what the exact issue was. nonetheless this update should be used moving forward since people use funder/sponsor synonymously in dandiset metadata.

### CODE REVIEW

**Comment by djarecka** [comment]
lgtm

**Comment by djarecka** [comment]
yes, looks like the error was not from `to_datacite`. During today meeting I was testing, but either I did something wrong, or I was getting inconsistent results... will update on slack

**Comment by djarecka** [comment]
I think my inconsistent results could be because [clean_doi](https://github.com/dandi/dandi-schema/blob/4e35300ace2868831372ab958bc64852dc8582f5/dandischema/tests/test_datacite.py#L40) doesn't work as expected...

Any idea why I get `*** requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://api.test.datacite.org/dois/10.80507/dandi.000333/0.0.0`

**Comment by satra** [comment]
did you call this function: https://github.com/dandi/dandi-schema/blob/4e35300ace2868831372ab958bc64852dc8582f5/dandischema/tests/test_datacite.py#L17 ? 

if so the doi has already been deleted because of the last step.

**Comment by djarecka** [comment]
but you can check that `https://api.test.datacite.org/dois/10.80507/dandi.000333/0.0.0` exists

**Comment by satra** [comment]
i don't know what's going on, but have you tried running the other function so that it posts and deletes? that should tell you it's working or not.

**Comment by djarecka** [comment]
usually it works... but have no idea what is wrong with my small test, will debug a bit longer...

**Comment by djarecka** [comment]
it looks the method `clean_doi` doesn't work after running `to_datacite` with `publish=True` (additional `attributes["event"] = "publish"` is added). Do you understand why?

**Comment by djarecka** [comment]
Just to update here:
- @satra explained to me that it is expected that if `to_datacite` is used with `publish=True` `clean_doi` will not delete the doi
- I've tried again running `to_datacite` and `datacite_post` on metadata from [`000458`](https://api.dandiarchive.org/api/dandisets/000458/versions/0.230317.0039/) (after changing id, since I'm still not sure how to remove doi that I created last week) and it works. This is the exact code I run (in `test_datacite`:
```
dandi_id = metadata["identifier"]
dandi_id_noprefix = dandi_id.split(":")[1]
metadata.update(_basic_publishmeta(dandi_id=dandi_id_noprefix))
datacite = to_datacite(metadata)
datacite_post(datacite, metadata["doi"])
```

- I've tried this for `https://api.test.datacite.org`. If I have to check for a different one, let me know

**Comment by satra** [comment]
thanks @djarecka - did you try it with the specific metadata that failed on dandiarchive with the current released code (i.e. that there was an issue before) and this branch (now it works)?

**Comment by djarecka** [comment]
I used the link for 458 that you pointed me to on Friday.

Sorry, forgot to add that I don't have any issue with master, so still seems like I'm not recreating the initial problem

**Comment by mvandenburgh** [comment]
> @mvandenburgh - is there a way you can try to retrigger the doi generation on the server side for that dandiset that did not get a doi?

Yes. Should I retrigger the doi generation with the code in this PR?

**Comment by satra** [comment]
@mvandenburgh - i would retest with what's on the server itself, since @djarecka can't replicate the issue with current main branch of this repo (without this PR).

**Comment by yarikoptic** [comment]
I wonder if worth 
- make sure that the test record doesn't have funderidtype while funderid is there. 
- if no error -- ask datacite folks why there is no error and show the error we received from a real server

**Comment by djarecka** [comment]
@mvandenburgh - could you please try to post the DOI with this branch? I've tested it in test `https://api.test.datacite.org/dois` with `publish=True`.

During the meeting on Monday I mentioned that `api.test.datacite` doesn't behave as `api.datacite`, but after checking carefully, that was my mistake, so hopefully this will solve the problem also with `api.datacite`

**Comment by djarecka** [comment]
@jwodder - do you know why dandi-cli are failing, not sure if the error comes from these changes...

**Comment by jwodder** [comment]
@djarecka See https://github.com/dandi/dandi-cli/pull/1243#issuecomment-1554480467.

**Pull request merged**
