### PR TITLE
Express DANDI data models in LinkML

### PR DESCRIPTION
**Pull request by candleindark**
The goal of this PR is to provide representations of DANDI data models in LinkML.

The initial representations in LinkML are generated with https://github.com/candleindark/linkml-aind-model a fork of https://github.com/DailyDreaming/linkml-aind-model.

Incremental targets:

- [x] Develop the tool at https://github.com/candleindark/linkml-aind-model to produce more correct and complete conversion from Pydantic models to a LinkML schema
- [x] Set up  a CI project to check various existing data instances against the produced LinkML schema
- [ ] Use the produced LinkML schema to produce Pydantic models to replace the existing Pydantic models in the `dandi-schema` project and check how well the existing tests in the project pass.
- [ ] Repeat the above steps to obtain a more complete and accurate LinkML schema if needed

### CODE REVIEW

**Comment by djarecka** [comment]
@candleindark - can you point me to the newest version of the linkml schema. The links posints to versions that are 5-8months old

**Comment by candleindark** [comment]
@djarecka You can generate the current schema using https://github.com/candleindark/pydantic2linkml/tree/enh (make sure it is the `enh` branch), by running `pydantic2linkml -o dandi-linkml-schema.yml dandischema.models`.

I will also make the latest DANDI LinkML schema available on https://github.com/dandi/dandisets-linkml-status, as part of the report directory, later today as well.

**Comment by djarecka** [comment]
perhaps you can add it to github (even if it's not final), so I can point someone to it

**Comment by candleindark** [comment]
I will provide a link to it at https://github.com/dandi/dandisets-linkml-status/blob/main/dandi-reports/summary.md. https://github.com/dandi/dandisets-linkml-status/tree/main will provide some the up-to-date info on the conversion of Dandi models to LinkML.

**Comment by candleindark** [comment]
@djarecka The latest generated DANDI LinkML schema is now referenced on https://github.com/dandi/dandisets-linkml-status/blob/main/dandi-reports/summary.md.

**Comment by candleindark** [comment]
I am closing this PR. It is no longer relevant. An up-to-date DANDI LinkML schema is now always referenced at https://github.com/dandi/dandisets-linkml-status/blob/main/dandi-reports/summary.md along with the validation results of dandiset metadata against it.

**Pull request closed without merging**
