### PR TITLE
[CFG] set minimum python version to 3.8

### PR DESCRIPTION
**Pull request by satra**
in keeping with numpy's policy: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

### CODE REVIEW

**Comment by satra** [comment]
@jwodder and @yarikoptic - i'm ready to merge this, but will wait to see what else needs to happen in our ecosystem.

**Comment by yarikoptic** [comment]
**I would prefer to keep minimal supported version of Python to be the minimal supported version of our tools.**

Rationale: If people could just afford to not install new scientific stack (numpy etc) on their systems, we often demand people to upgrade their dandi-cli to the most recent release just to be able to download or upload data. So making it unaffordable for them to use outdated version of `dandi-cli`, possibly the "latest" supported  on their "supported" version of Python with still available for that Python numpy etc.  Hence, to not demand users to upgrade their entire stack (Python, numpy, etc) to merely upload/download data to/from the archive, I would prefer to align with the EOL cycle of Python itself: https://endoflife.date/python .

Having stated that, if at some point we consciously decide to drop some supported Python version due to some grave issue or that compatibility with it becomes difficult, or some really useful new feature added in some newer Python -- I would be open to have such minimal version boosted then.  Insofar, I saw no such need/desires to warrant dropping supported 3.7 .  Sure thing some downstream projects like hdmf (attn @rly @bendichter @oruebel) could force us to act by dropping compatibility .

I am open for discussion though - may be I am missing some good reasons to demand our users to chase the train.

**Comment by candleindark** [comment]
Since #193 has been merged, does that mean everyone agrees to drop support for Python 3.7 at this point?

**Comment by yarikoptic** [comment]
> Since #193 has been merged, does that mean everyone agrees to drop support for Python 3.7 at this point?

yes, 3.7 EOLed fully by now.

**Comment by candleindark** [comment]
> > Since #193 has been merged, does that mean everyone agrees to drop support for Python 3.7 at this point?
> 
> yes, 3.7 EOLed fully by now.

Will someone merge this PR?

**Comment by yarikoptic** [comment]
nobody will merge it until it is redone or conflicts are resolved.  Could you redo it (I think easier than merge conflicts) @candleindark ?

**Comment by candleindark** [comment]
> nobody will merge it until it is redone or conflicts are resolved. Could you redo it (I think easier than merge conflicts) @candleindark ?

OK. I will look into it but possibly will get the Pydantic upgrade working first.

**Comment by satra** [comment]
closing this for now 3.8 is out the door almost at this point.

**Pull request closed without merging**
