### PR TITLE
Draft: Relax timestamp timezone validation for startDate and endDate fields on NWB file formats

### PR DESCRIPTION
**Pull request by aaronkanzer**
Relates to https://github.com/dandi/dandi-archive/issues/1944

and changes made for NWB in https://github.com/NeurodataWithoutBorders/pynwb/pull/1886

Observed in failed dandiset validation in staging environment here: https://gui-staging.dandiarchive.org/dandiset/213840

Cc @candleindark @yarikoptic @satra @bendichter

### CODE REVIEW

**Comment by satra** [comment]
@aaronkanzer - i'm not sure this is necessary. i believe pydantic default validator for datetime works fine. at least on the example ben sent.

**Comment by aaronkanzer** [comment]
> @aaronkanzer - i'm not sure this is necessary. i believe pydantic default validator for datetime works fine. at least on the example ben sent.

Hmmm, yeah accordingly to the docs _it should_ work fine (e.g. pydantic handling different formats of `datetime`), but it is still failing 🤔 

Perhaps a different root cause....looking further...

**Comment by bendichter** [comment]
Yes, this is what has been confusing us. We don't see any logic in the dandi schema that would seem to require timezones for this field

**Comment by aaronkanzer** [comment]
Closed for now -- as it doesn't seem that this is the root cause error of validation for certain `datetime` timestamps.

**Pull request closed without merging**
